    sources:
      - InstrumentSans.glyphs
      - InstrumentSans-Italic.glyphs
    axisOrder:
      - wdth
      - wght
      - ital
    familyName: Instrument Sans
    stat:
      InstrumentSans[wdth,wght].ttf:
      - name: Width
        tag: wdth
        values:
        - name: Condensed
          value: 75
        - name: SemiCondensed
          value: 87.5
        - name: Normal
          value: 100
          flags: 2
      - name: Weight
        tag: wght
        values:
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 2
      InstrumentSans-Italic[wdth,wght].ttf:
      - name: Width
        tag: wdth
        values:
        - name: Condensed
          value: 75
        - name: SemiCondensed
          value: 87.5
        - name: Normal
          value: 100
          flags: 2
      - name: Weight
        tag: wght
        values:
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
      - name: Italic
        tag: ital
        values:
        - name: Italic
          value: 1
          